//go:build ignore

// gen_command_index.go regenerates docs/COMMAND_INDEX.md: a complete index of every
// cmd/* command, with a one-line description and a run example pulled from each
// command's own package doc comment. Run it from the repo root:
//
//	go run scripts/gen_command_index.go
package main

import (
	"fmt"
	"go/doc"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type entry struct {
	name, desc, run string
}

// firstSentence collapses a doc comment to its first sentence (newlines to spaces),
// capped so the index stays a table.
func firstSentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	// stop at a blank line (paragraph break) first
	if i := strings.Index(s, "\n\n"); i >= 0 {
		s = s[:i]
	}
	s = strings.Join(strings.Fields(s), " ") // newlines/tabs -> single spaces
	// cut at the first sentence-ending period followed by a space
	for i := 0; i < len(s)-1; i++ {
		if s[i] == '.' && s[i+1] == ' ' {
			s = s[:i+1]
			break
		}
	}
	if len(s) > 200 { // always cap so the index stays a tidy table
		s = strings.TrimSpace(s[:200]) + "…"
	}
	return s
}

func packageDoc(dir string) string {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), ".go") && !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return ""
	}
	// prefer the "main" package; fall back to any package that carries a doc
	if p, ok := pkgs["main"]; ok {
		if d := doc.New(p, dir, 0).Doc; d != "" {
			return d
		}
	}
	for _, p := range pkgs {
		if d := doc.New(p, dir, 0).Doc; d != "" {
			return d
		}
	}
	return ""
}

func main() {
	dirs, _ := filepath.Glob("cmd/*")
	var ents []entry
	for _, dir := range dirs {
		fi, err := os.Stat(dir)
		if err != nil || !fi.IsDir() {
			continue
		}
		name := filepath.Base(dir)
		d := packageDoc(dir)
		desc := firstSentence(d)
		// strip the "Command <name> is/—" lead-in so the cell reads as a description
		for _, p := range []string{"Command " + name + " is ", "Command " + name + " — ", "Command " + name + " "} {
			if strings.HasPrefix(desc, p) {
				desc = strings.TrimPrefix(desc, p)
				break
			}
		}
		if desc != "" { // capitalise the first letter for polish
			desc = strings.ToUpper(desc[:1]) + desc[1:]
		} else {
			desc = "(see `go doc ./" + dir + "`)"
		}
		desc = strings.ReplaceAll(desc, "|", "\\|") // keep the markdown table intact
		run := "go run ./" + dir
		for _, line := range strings.Split(d, "\n") {
			if l := strings.TrimSpace(line); strings.HasPrefix(l, "go run ") {
				if h := strings.Index(l, "#"); h >= 0 { // drop trailing "# comment"
					l = strings.TrimSpace(l[:h])
				}
				run = l
				break
			}
		}
		ents = append(ents, entry{name, desc, run})
	}
	sort.Slice(ents, func(i, j int) bool { return ents[i].name < ents[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, "# Command index — all %d commands\n\n", len(ents))
	b.WriteString("_Auto-generated by `go run scripts/gen_command_index.go` from each command's\n")
	b.WriteString("package doc comment — do not edit by hand. For fuller usage of one command run\n")
	b.WriteString("`go doc ./cmd/<name>`; for a curated quick start and the ray/Q6/alife platform see\n")
	b.WriteString("[COMMANDS.md](COMMANDS.md); for what the project is and how it composes see\n")
	b.WriteString("[CONCEPT_MAP.md](CONCEPT_MAP.md)._\n\n")
	b.WriteString("| Command | What it is | Run |\n|---|---|---|\n")
	for _, e := range ents {
		fmt.Fprintf(&b, "| `%s` | %s | `%s` |\n", e.name, e.desc, e.run)
	}

	out := filepath.Join("docs", "COMMAND_INDEX.md")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d commands)\n", out, len(ents))
}
